# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    elevator.commands:
        'Waiting External':
            id: !php/const:AppBundle\Elevator\Command\WaitingExternal::ID
            injection: command.waiting_external
        'Moving':
            id: !php/const:AppBundle\Elevator\Command\Moving::ID
            injection: command.moving
        'Open The Doors':
            id: !php/const:AppBundle\Elevator\Command\OpenTheDoors::ID
            injection: command.open_the_doors

services:
    command.waiting_external:
        class: AppBundle\Elevator\Command\WaitingExternal
        arguments: ['@command_factory', '@amqp.connect.input.external']
        shared: false

    command.moving:
        class: AppBundle\Elevator\Command\Moving
        arguments: ['@command_factory']
        shared: false

    command.open_the_doors:
        class: AppBundle\Elevator\Command\OpenTheDoors
        arguments: ['@command_factory']
        shared: false

    amqp.connect:
        class: PhpAmqpLib\Connection\AMQPStreamConnection
        arguments: ['%amqp_host%', '%amqp_port%', '%amqp_user%', '%amqp_password%']

    amqp.connect.input.external:
        class: AppBundle\Elevator\AmqpConnect
        arguments: ['@amqp.connect', '%ampq_queue_waiting_external%']

    amqp.connect.input.internal:
        class: AppBundle\Elevator\AmqpConnection
        arguments: ['@amqp.connect', test-connection-02]

    elevator:
        class: AppBundle\Elevator\Elevator
        arguments: ['%elevator_total_floors%', '%elevator_speed%', '%elevator_doors_activity_time%', '%elevator_initial_floor%']

    command_factory:
        class: AppBundle\Elevator\CommandFactory
        arguments: ['@service_container', %elevator.commands%]

    elevator_emulate:
        class: AppBundle\Elevator\Device
        arguments: ['@command.waiting_external', '@elevator']
        autowire: true
